export const mockCategories = [
  {
    id: "cat-1",
    name: "AI Smartphones",
    slug: "ai-smartphones",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop",
    icon: "Smartphone",
    featured: true,
    productCount: 24,
  },
  {
    id: "cat-2",
    name: "Laptops & Computers",
    slug: "laptops-computers",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop",
    icon: "Laptop",
    featured: true,
    productCount: 18,
  },
  {
    id: "cat-3",
    name: "TVs & Home Theatre",
    slug: "tvs-home-theatre",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop",
    icon: "Tv",
    featured: true,
    productCount: 15,
  },
  {
    id: "cat-4",
    name: "Home Appliances",
    slug: "home-appliances",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
    icon: "Refrigerator",
    featured: true,
    productCount: 32,
  },
  {
    id: "cat-5",
    name: "Audio & Headphones",
    slug: "audio-headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
    icon: "Headphones",
    featured: true,
    productCount: 20,
  },
  {
    id: "cat-6",
    name: "Gaming & Consoles",
    slug: "gaming-consoles",
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400&h=300&fit=crop",
    icon: "Gamepad2",
    featured: true,
    productCount: 12,
  },
  {
    id: "cat-7",
    name: "Networking",
    slug: "networking",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&h=300&fit=crop",
    icon: "Wifi",
    featured: false,
    productCount: 10,
  },
  {
    id: "cat-8",
    name: "Printers & Office",
    slug: "printers-office",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&h=300&fit=crop",
    icon: "Printer",
    featured: false,
    productCount: 14,
  },
];

export const mockBrands = [
  { id: "brand-1", name: "Samsung", slug: "samsung", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/200px-Samsung_Logo.svg.png" },
  { id: "brand-2", name: "Apple", slug: "apple", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/100px-Apple_logo_black.svg.png" },
  { id: "brand-3", name: "HP", slug: "hp", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/HP_logo_2012.svg/150px-HP_logo_2012.svg.png" },
  { id: "brand-4", name: "LG", slug: "lg", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/LG_logo_%282015%29.svg/150px-LG_logo_%282015%29.svg.png" },
  { id: "brand-5", name: "Sony", slug: "sony", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sony_logo.svg/200px-Sony_logo.svg.png" },
  { id: "brand-6", name: "Dell", slug: "dell", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Dell_Logo.svg/150px-Dell_Logo.svg.png" },
  { id: "brand-7", name: "Lenovo", slug: "lenovo", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lenovo_logo_2015.svg/200px-Lenovo_logo_2015.svg.png" },
  { id: "brand-8", name: "JBL", slug: "jbl", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/JBL_logo.svg/150px-JBL_logo.svg.png" },
];

export const mockProducts = [
  {
    id: "prod-1",
    name: "Samsung Galaxy S24 Ultra 256GB",
    slug: "samsung-galaxy-s24-ultra-256gb",
    description: "Experience the pinnacle of mobile innovation with Galaxy AI. The Samsung Galaxy S24 Ultra features a stunning 6.8-inch Dynamic AMOLED display, 200MP camera system, and the powerful Snapdragon 8 Gen 3 processor. Built with titanium frame for durability and elegance.",
    price: 15999.00,
    comparePrice: 17999.00,
    sku: "SAM-S24U-256",
    stock: 15,
    images: [
      { id: "img-1", url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop", alt: "Samsung Galaxy S24 Ultra" },
      { id: "img-2", url: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&h=600&fit=crop", alt: "Samsung Galaxy S24 Ultra Back" },
    ],
    categoryId: "cat-1",
    category: { id: "cat-1", name: "AI Smartphones", slug: "ai-smartphones" },
    brandId: "brand-1",
    brand: { id: "brand-1", name: "Samsung", slug: "samsung" },
    featured: true,
    isNew: true,
    onSale: true,
    rating: 4.8,
    reviewCount: 124,
    tags: "samsung,galaxy,s24,ultra,ai,smartphone",
  },
  {
    id: "prod-2",
    name: "MacBook Pro 14\" M3 Pro 512GB",
    slug: "macbook-pro-14-m3-pro-512gb",
    description: "The most advanced Mac laptop ever. Supercharged by the M3 Pro chip for exceptional performance. Features a stunning Liquid Retina XDR display, up to 18 hours of battery life, and a sophisticated design in Space Black or Silver.",
    price: 24999.00,
    comparePrice: 27999.00,
    sku: "APL-MBP14-M3P",
    stock: 8,
    images: [
      { id: "img-3", url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop", alt: "MacBook Pro 14" },
      { id: "img-4", url: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&h=600&fit=crop", alt: "MacBook Pro 14 Open" },
    ],
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Laptops & Computers", slug: "laptops-computers" },
    brandId: "brand-2",
    brand: { id: "brand-2", name: "Apple", slug: "apple" },
    featured: true,
    isNew: true,
    onSale: true,
    rating: 4.9,
    reviewCount: 89,
    tags: "apple,macbook,pro,m3,laptop",
  },
  {
    id: "prod-3",
    name: "LG 65\" OLED C4 4K Smart TV",
    slug: "lg-65-oled-c4-4k-smart-tv",
    description: "Immerse yourself in breathtaking visuals with the LG OLED C4. Perfect blacks, infinite contrast, and vibrant colors powered by the α9 AI Processor 4K Gen7. Dolby Vision, Dolby Atmos, and webOS for endless entertainment.",
    price: 18500.00,
    comparePrice: 22000.00,
    sku: "LG-OLED65C4",
    stock: 5,
    images: [
      { id: "img-5", url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=600&fit=crop", alt: "LG OLED TV" },
    ],
    categoryId: "cat-3",
    category: { id: "cat-3", name: "TVs & Home Theatre", slug: "tvs-home-theatre" },
    brandId: "brand-4",
    brand: { id: "brand-4", name: "LG", slug: "lg" },
    featured: true,
    isNew: false,
    onSale: true,
    rating: 4.7,
    reviewCount: 56,
    tags: "lg,oled,tv,4k,smart-tv",
  },
  {
    id: "prod-4",
    name: "Sony WH-1000XM5 Wireless Headphones",
    slug: "sony-wh-1000xm5-wireless-headphones",
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours of battery life. Exceptionally comfortable ultralight design.",
    price: 3299.00,
    comparePrice: 3999.00,
    sku: "SONY-WH1000XM5",
    stock: 25,
    images: [
      { id: "img-6", url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop", alt: "Sony WH-1000XM5" },
    ],
    categoryId: "cat-5",
    category: { id: "cat-5", name: "Audio & Headphones", slug: "audio-headphones" },
    brandId: "brand-5",
    brand: { id: "brand-5", name: "Sony", slug: "sony" },
    featured: true,
    isNew: false,
    onSale: true,
    rating: 4.6,
    reviewCount: 203,
    tags: "sony,headphones,wireless,noise-cancelling",
  },
  {
    id: "prod-5",
    name: "iPhone 15 Pro Max 256GB",
    slug: "iphone-15-pro-max-256gb",
    description: "Forged in titanium. iPhone 15 Pro Max features a strong and lightweight aerospace-grade titanium design. A17 Pro chip, 48MP camera system, and the longest optical zoom ever on iPhone. Action button for instant access.",
    price: 18999.00,
    comparePrice: 19999.00,
    sku: "APL-IP15PM-256",
    stock: 12,
    images: [
      { id: "img-7", url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop", alt: "iPhone 15 Pro Max" },
    ],
    categoryId: "cat-1",
    category: { id: "cat-1", name: "AI Smartphones", slug: "ai-smartphones" },
    brandId: "brand-2",
    brand: { id: "brand-2", name: "Apple", slug: "apple" },
    featured: true,
    isNew: true,
    onSale: false,
    rating: 4.9,
    reviewCount: 156,
    tags: "apple,iphone,15,pro,max",
  },
  {
    id: "prod-6",
    name: "HP Pavilion 15 AMD Ryzen 7",
    slug: "hp-pavilion-15-amd-ryzen-7",
    description: "Power through your day with the HP Pavilion 15. AMD Ryzen 7 processor, 16GB RAM, 512GB SSD, and a vibrant 15.6-inch FHD display. Perfect for productivity, creativity, and entertainment.",
    price: 8999.00,
    comparePrice: 10999.00,
    sku: "HP-PAV15-R7",
    stock: 10,
    images: [
      { id: "img-8", url: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=600&fit=crop", alt: "HP Pavilion 15" },
    ],
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Laptops & Computers", slug: "laptops-computers" },
    brandId: "brand-3",
    brand: { id: "brand-3", name: "HP", slug: "hp" },
    featured: false,
    isNew: false,
    onSale: true,
    rating: 4.3,
    reviewCount: 67,
    tags: "hp,pavilion,laptop,ryzen",
  },
  {
    id: "prod-7",
    name: "Samsung 55\" Crystal UHD 4K TV",
    slug: "samsung-55-crystal-uhd-4k-tv",
    description: "See every detail in stunning 4K clarity. The Crystal Processor 4K delivers crisp and vivid colors. Smart TV powered by Tizen with access to all your favorite streaming apps.",
    price: 7499.00,
    comparePrice: 8999.00,
    sku: "SAM-CU55-4K",
    stock: 20,
    images: [
      { id: "img-9", url: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&h=600&fit=crop", alt: "Samsung Crystal UHD TV" },
    ],
    categoryId: "cat-3",
    category: { id: "cat-3", name: "TVs & Home Theatre", slug: "tvs-home-theatre" },
    brandId: "brand-1",
    brand: { id: "brand-1", name: "Samsung", slug: "samsung" },
    featured: true,
    isNew: false,
    onSale: true,
    rating: 4.5,
    reviewCount: 89,
    tags: "samsung,tv,4k,uhd,crystal",
  },
  {
    id: "prod-8",
    name: "JBL Charge 5 Portable Speaker",
    slug: "jbl-charge-5-portable-speaker",
    description: "Bold sound and powerful bass in a portable package. IP67 waterproof and dustproof. 20 hours of playtime. Built-in power bank to charge your devices. JBL PartyBoost for amplified fun.",
    price: 1599.00,
    comparePrice: 1999.00,
    sku: "JBL-CHG5",
    stock: 30,
    images: [
      { id: "img-10", url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop", alt: "JBL Charge 5" },
    ],
    categoryId: "cat-5",
    category: { id: "cat-5", name: "Audio & Headphones", slug: "audio-headphones" },
    brandId: "brand-8",
    brand: { id: "brand-8", name: "JBL", slug: "jbl" },
    featured: true,
    isNew: false,
    onSale: true,
    rating: 4.7,
    reviewCount: 312,
    tags: "jbl,speaker,portable,bluetooth",
  },
  {
    id: "prod-9",
    name: "PlayStation 5 Console Bundle",
    slug: "playstation-5-console-bundle",
    description: "Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio. Includes DualSense controller and 2 games.",
    price: 8499.00,
    comparePrice: 9499.00,
    sku: "SONY-PS5-BDL",
    stock: 7,
    images: [
      { id: "img-11", url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop", alt: "PlayStation 5" },
    ],
    categoryId: "cat-6",
    category: { id: "cat-6", name: "Gaming & Consoles", slug: "gaming-consoles" },
    brandId: "brand-5",
    brand: { id: "brand-5", name: "Sony", slug: "sony" },
    featured: true,
    isNew: false,
    onSale: true,
    rating: 4.8,
    reviewCount: 178,
    tags: "sony,playstation,ps5,gaming,console",
  },
  {
    id: "prod-10",
    name: "Dell Inspiron 16 2-in-1 Laptop",
    slug: "dell-inspiron-16-2-in-1-laptop",
    description: "Versatile 2-in-1 design with 360° hinge. Intel Core i7, 16GB RAM, 1TB SSD. 16-inch FHD+ touchscreen with active pen support. Perfect for work, creativity, and entertainment.",
    price: 12999.00,
    comparePrice: 14999.00,
    sku: "DEL-INS16-2IN1",
    stock: 6,
    images: [
      { id: "img-12", url: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=600&h=600&fit=crop", alt: "Dell Inspiron 16" },
    ],
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Laptops & Computers", slug: "laptops-computers" },
    brandId: "brand-6",
    brand: { id: "brand-6", name: "Dell", slug: "dell" },
    featured: false,
    isNew: true,
    onSale: true,
    rating: 4.4,
    reviewCount: 45,
    tags: "dell,inspiron,2-in-1,laptop,touchscreen",
  },
  {
    id: "prod-11",
    name: "Samsung Side-by-Side Refrigerator 680L",
    slug: "samsung-side-by-side-refrigerator-680l",
    description: "SpaceMax Technology provides more storage space inside. All-around Cooling maintains consistent temperature. Digital Inverter Compressor for energy efficiency and quiet operation.",
    price: 14500.00,
    comparePrice: 16999.00,
    sku: "SAM-SBS680",
    stock: 4,
    images: [
      { id: "img-13", url: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&h=600&fit=crop", alt: "Samsung Refrigerator" },
    ],
    categoryId: "cat-4",
    category: { id: "cat-4", name: "Home Appliances", slug: "home-appliances" },
    brandId: "brand-1",
    brand: { id: "brand-1", name: "Samsung", slug: "samsung" },
    featured: false,
    isNew: false,
    onSale: true,
    rating: 4.6,
    reviewCount: 34,
    tags: "samsung,refrigerator,side-by-side,appliance",
  },
  {
    id: "prod-12",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    slug: "lenovo-thinkpad-x1-carbon-gen-11",
    description: "The iconic business ultrabook, lighter and more powerful than ever. 13th Gen Intel Core i7, 16GB RAM, 512GB SSD. 14-inch 2.8K OLED display. MIL-SPEC tested durability.",
    price: 19999.00,
    comparePrice: 22999.00,
    sku: "LEN-X1C-G11",
    stock: 5,
    images: [
      { id: "img-14", url: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=600&fit=crop", alt: "Lenovo ThinkPad X1" },
    ],
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Laptops & Computers", slug: "laptops-computers" },
    brandId: "brand-7",
    brand: { id: "brand-7", name: "Lenovo", slug: "lenovo" },
    featured: true,
    isNew: true,
    onSale: true,
    rating: 4.7,
    reviewCount: 78,
    tags: "lenovo,thinkpad,x1,carbon,business,laptop",
  },
];

export const mockHeroSlides = [
  {
    id: "slide-1",
    title: "Racing With Technology",
    subtitle: "Ghana's #1 Electronics Destination",
    description: "Discover the latest smartphones, laptops, TVs, and more at unbeatable prices. Free delivery on orders over GH₵3,000.",
    image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1920&h=800&fit=crop",
    buttonText: "Shop Now",
    buttonLink: "/shop",
  },
  {
    id: "slide-2",
    title: "AI-Powered Smartphones",
    subtitle: "The Future is Here",
    description: "Experience the latest AI-enabled smartphones from Samsung, Apple, and more. Transform how you work, create, and connect.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1920&h=800&fit=crop",
    buttonText: "Explore AI Phones",
    buttonLink: "/shop/ai-smartphones",
  },
  {
    id: "slide-3",
    title: "Home Entertainment Redefined",
    subtitle: "Cinematic Experience at Home",
    description: "From OLED TVs to surround sound systems, create the ultimate home theatre experience with our premium selection.",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1920&h=800&fit=crop",
    buttonText: "Shop TVs",
    buttonLink: "/shop/tvs-home-theatre",
  },
];

export type MockProduct = (typeof mockProducts)[number];
export type MockCategory = (typeof mockCategories)[number];
